on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAYJUJXTH3GQZVLDV5
          aws-secret-access-key: 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
          aws-region: ap-northeast-2
      # Build inside Docker containers
      - run: sam build --use-container
      # Prevent p
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
